---
title: "Tables"
author: "Arthur M. Albuquerque"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
          code_folding: hide
          toc: yes
          toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, results = 'hide'}
# Load packages

# Ensures the package "pacman" is installed
if (!require("pacman")) install.packages("pacman")

pacman::p_load(here,
               rio,
               dplyr,
               brms,
               tidybayes,
               gt)

# Ensure that packages are installed according to versions in renv's lockfile
renv::restore()

# Load table 1 data
pre_table1 = rio::import(
  here::here("data", "table1_data.xlsx")
)


# Load meta-regressions

# Sari vs. Toci
mr_sari_skeptical = readRDS(here::here("output", "fits",
                                       "mr_sari_skeptical.Rds"))
mr_sari_optimistic_sari_remapcap =
  readRDS(here::here("output", "fits", "sensitivity_analyses",
                     "mr_sari_optimistic_sari_remapcap.Rds"))
mr_sari_optimistic_toci_remapcap =
  readRDS(here::here("output", "fits", "sensitivity_analyses",
                     "mr_sari_optimistic_toci_remapcap.Rds"))
mr_sari_vague = readRDS(here::here("output", "fits",
                                   "mr_sari_vague.Rds"))

# Bari vs. Toci

mr_bari_skeptical = readRDS(here::here("output", "fits",
                                       "mr_bari_skeptical.Rds"))
mr_bari_optimistic_bari = readRDS(here::here("output", "fits",
                                             "mr_bari_optimistic_bari.Rds"))
mr_bari_optimistic_toci = readRDS(here::here("output", "fits",
                                             "mr_bari_optimistic_toci.Rds"))
mr_bari_vague = readRDS(here::here("output", "fits",
                                   "mr_bari_vague.Rds"))

# Sensitivity analysis

mr_bari_skeptical_sens = readRDS(here::here("output", "fits",
                                       "mr_bari_skeptical_sens.Rds"))
mr_bari_optimistic_bari_sens = readRDS(here::here("output", "fits",
                                             "mr_bari_optimistic_bari_sens.Rds"))
mr_bari_optimistic_toci_sens = readRDS(here::here("output", "fits",
                                             "mr_bari_optimistic_toci_sens.Rds"))
mr_bari_vague_sens = readRDS(here::here("output", "fits",
                                   "mr_bari_vague_sens.Rds"))

```

# Table 1

Overall characteristics of included RCTs

```{r}
pre_table1 |>  
  # Re-order columns
  dplyr::select(study_name, intervention,
                age_control, male_control, time_symptom_control, pcr_control,
                simple_oxygen_control, niv_control, imv_control,
                age_exp, male_exp, time_symptom_exp, pcr_exp,
                simple_oxygen_exp, niv_exp, imv_exp
                ) |> 
  dplyr::rename("Study" = study_name,
                "Age" = age_control,
                "Male"= male_control,
                "Time since Symptom Onset" = time_symptom_control,
                "Lab Confirmed COVID-19" = pcr_control,
                "Simple Oxygen Only" = simple_oxygen_control,
                "Noninvasive Ventilation" = niv_control,
                "Invasive Mechanical Ventilation" = imv_control,
                
                "Age " = age_exp,
                "Male "= male_exp,
                "Time since Symptom Onset " = time_symptom_exp,
                "Lab Confirmed COVID-19 " = pcr_exp,
                "Simple Oxygen Only " = simple_oxygen_exp,
                "Noninvasive Ventilation " = niv_exp,
                "Invasive Mechanical Ventilation " = imv_exp
                ) |> 
  dplyr::group_by(intervention) |> 
  gt::gt() |> 
  gt::tab_spanner(label = "Control Treatment",
                  columns = 2:9) |> 
  gt::tab_spanner(label = "Experimental Treatment",
                  columns = 10:dplyr::last_col()) |> 
  gt::tab_footnote(
    footnote = "Median (IQR) or Mean (SD)",
    locations = gt::cells_column_labels(
      columns = c("Age", "Age ",
                  "Time since Symptom Onset", "Time since Symptom Onset ",
                  )
      )
    ) |> 
  gt::tab_footnote(
    footnote = "%",
    locations = gt::cells_column_labels(
      columns = c("Male", "Male ",
                  "Lab Confirmed COVID-19", "Lab Confirmed COVID-19 ",
                  "Simple Oxygen Only", "Simple Oxygen Only ",
                  "Noninvasive Ventilation", "Noninvasive Ventilation ",
                  "Invasive Mechanical Ventilation", "Invasive Mechanical Ventilation "
                  )
      )
    ) |> 
  tab_source_note(
    source_note =
      md("Patient characteristics specific to those co-treated with corticosteroids were not systematically reported in these RCTs. Thus, this table includes characteristics to all participants randomized in these studies, and not necessarily to only patients treated with corticosteroids. "
  )
  ) |> 
  gtsave("table_1.html",
         path =  here("output", "tables"))
```

```{r}
# Function to extract posterior draws more easily

parameter_fun = function(model){
  model |>
    tidybayes::tidy_draws() |>
    tidyr::pivot_longer(5) # Beta_1 parameter (5th column)
}

draws_bari =
  dplyr::tibble(
    "vague" = parameter_fun(mr_bari_vague)$value,
    "skeptical" = parameter_fun(mr_bari_skeptical)$value,
    "optimistic_bari" = parameter_fun(mr_bari_optimistic_bari)$value,
    "optimistic_toci" = parameter_fun(mr_bari_optimistic_toci)$value
  ) |> 
  tidyr::pivot_longer(1:4)

draws_sari =
  dplyr::tibble(
    "vague" = parameter_fun(mr_sari_vague)$value,
    "skeptical" = parameter_fun(mr_sari_skeptical)$value,
    "optimistic_sari" = parameter_fun(mr_sari_optimistic_sari_remapcap)$value,
    "optimistic_toci" = parameter_fun(mr_sari_optimistic_toci_remapcap)$value
  ) |> 
  tidyr::pivot_longer(1:4)

draws_bari_sens =
  dplyr::tibble(
    "vague" = parameter_fun(mr_bari_vague_sens)$value,
    "skeptical" = parameter_fun(mr_bari_skeptical_sens)$value,
    "optimistic_bari" = parameter_fun(mr_bari_optimistic_bari_sens)$value,
    "optimistic_toci" = parameter_fun(mr_bari_optimistic_toci_sens)$value
  ) |> 
  tidyr::pivot_longer(1:4)
```


# Table 2

```{r}
ni_margin = log(1.139606)

# Bari
ror_bari = 
  draws_bari |> 
  dplyr::group_by(name) |> 
  ggdist::median_hdi(exp(value)) |> 
  dplyr::summarise(Belief = name,
                   "ROR (95% CrI)" = stringr::str_c(
                     round(`exp(value)`, 2),
                     " (", round(.lower, 2), ", ", round(.upper, 2), ")"
                     )
                   ) |> 
  dplyr::mutate(treatment = "Baricitinib vs. Tocilizumab")

proba_bari =
  draws_bari |> 
  dplyr::group_by(name) |> 
  dplyr::summarise("Probability of Noninferiority, %" =
                     100*round(mean(value < ni_margin),2),
                   "Probability of Superiority, %" =
                     100*round(mean(value < log(1)),2)
                   ) |> 
  dplyr::rename("Belief" = name)

results_bari = dplyr::left_join(ror_bari, proba_bari) |> 
  dplyr::mutate(
    Belief = dplyr::case_when(
      Belief == "vague" ~ "Vague",
      Belief == "skeptical" ~ "Skeptical",
      Belief == "optimistic_bari" ~ "Optimistic for Baricitinib",
      Belief == "optimistic_toci" ~ "Optimistic for Tocilizumab"),
    Belief = factor(Belief, levels = c("Vague",
                                       "Skeptical",
                                       "Optimistic for Baricitinib",
                                       "Optimistic for Tocilizumab"))
    ) |> 
  dplyr::arrange(Belief)

# Sari
ror_sari = 
  draws_sari |> 
  dplyr::group_by(name) |> 
  ggdist::median_hdi(exp(value)) |> 
  dplyr::summarise(Belief = name,
                   "ROR (95% CrI)" = stringr::str_c(
                     round(`exp(value)`, 2),
                     " (", round(.lower, 2), ", ", round(.upper, 2), ")"
                     )
                   ) |> 
  dplyr::mutate(treatment = "Sarilumab vs. Tocilizumab")

proba_sari =
  draws_sari |> 
  dplyr::group_by(name) |> 
  dplyr::summarise("Probability of Noninferiority, %" =
                     100*round(mean(value < ni_margin),2),
                   "Probability of Superiority, %" =
                     100*round(mean(value < log(1)),2)
                   ) |> 
  dplyr::rename("Belief" = name)

results_sari = dplyr::left_join(ror_sari, proba_sari) |> 
  dplyr::mutate(
    Belief = dplyr::case_when(
      Belief == "vague" ~ "Vague",
      Belief == "skeptical" ~ "Skeptical",
      Belief == "optimistic_sari" ~ "Optimistic for Sarilumab (REMAP-CAP)",
      Belief == "optimistic_toci" ~ "Optimistic for Tocilizumab (inverse REMAP-CAP)"),
    Belief = factor(Belief, levels = c("Vague",
                                       "Skeptical",
                                       "Optimistic for Sarilumab (REMAP-CAP)",
                                       "Optimistic for Tocilizumab (inverse REMAP-CAP)"))
    ) |> 
  dplyr::arrange(Belief)

pre_table2 = 
  dplyr::bind_rows(results_bari, results_sari) |> 
  dplyr::group_by(treatment)

saveRDS(pre_table2,
        here("output", "tables", "table_2_data.Rds"))


table2 = 
  pre_table2 |> 
  gt::gt() |> 
  gt::cols_align(
    align = "right",
    columns = everything()
    ) %>%
  gt::cols_align(
    align = "left",
    columns = "Belief"
    ) |> 
  gt::cols_width(
    Belief ~ px(250),
    "ROR (95% CrI)" ~ px(150),
    "Probability of Noninferiority, %" ~ px(110),
    "Probability of Superiority, %" ~ px(107)
    ) |> 
  gt::tab_footnote(
    footnote = "Posterior probability below the noninferiority margin (1.14 ROR)",
    locations = cells_column_labels(
      columns = c("Probability of Noninferiority, %")
    )
    ) |> 
  gt::tab_footnote(
    footnote = "Posterior probability below 1.0 ROR",
    locations = cells_column_labels(
      columns = c("Probability of Superiority, %")
    )
    ) |> 
  gt::tab_source_note(
    source_note =
      md("Abbreviations: ROR, ratio of odds ratios; CrI, credible interval")
  )

table2 |> 
 gt::gtsave("table_2.html",
        path =  here::here("output", "tables"))


```


# Sensitivity analysis


```{r}
# Bari
ror_bari_sens = 
  draws_bari_sens |> 
  dplyr::group_by(name) |> 
  ggdist::median_hdi(exp(value)) |> 
  dplyr::summarise(Belief = name,
                   "ROR (95% CrI)" = stringr::str_c(
                     round(`exp(value)`, 2),
                     " (", round(.lower, 2), ", ", round(.upper, 2), ")"
                     )
                   ) |> 
  dplyr::mutate(treatment = "Baricitinib vs. Tocilizumab")

proba_bari_sens =
  draws_bari_sens |> 
  dplyr::group_by(name) |> 
  dplyr::summarise("Probability of Noninferiority, %" =
                     100*round(mean(value < ni_margin),2),
                   "Probability of Superiority, %" =
                     100*round(mean(value < log(1)),2)
                   ) |> 
  dplyr::rename("Belief" = name)

pre_table_sens = dplyr::left_join(ror_bari_sens, proba_bari_sens) |> 
  dplyr::mutate(
    Belief = dplyr::case_when(
      Belief == "vague" ~ "Vague",
      Belief == "skeptical" ~ "Skeptical",
      Belief == "optimistic_bari" ~ "Optimistic for Baricitinib",
      Belief == "optimistic_toci" ~ "Optimistic for Tocilizumab"),
    Belief = factor(Belief, levels = c("Vague",
                                       "Skeptical",
                                       "Optimistic for Baricitinib",
                                       "Optimistic for Tocilizumab"))
    ) |> 
  dplyr::arrange(Belief) |> 
  dplyr::group_by(treatment)

saveRDS(pre_table_sens,
        here("output", "tables", "supplementary", "table_sens_data.Rds"))

```




