---
title: "Meta-regressions Figure"
author: "Arthur M. Albuquerque"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r message=FALSE, warning=FALSE, results = 'hide'}
# Load packages

# Ensures the package "pacman" is installed
if (!require("pacman")) install.packages("pacman")

pacman::p_load(here,
               rio,
               dplyr,
               ggplot2,
               brms,
               tidybayes,
               patchwork,
               cowplot,
               pdftools,
               gt,
               MetBrewer)

# Ensure that packages are installed according to versions in renv's lockfile
renv::restore()

# Colors
pal = MetBrewer::met.brewer(name="Lakota",n=6,type="discrete")
pal_toci = MetBrewer::met.brewer(name="OKeeffe2",n=7,type="discrete")
pal_bari_sari = MetBrewer::met.brewer(name="VanGogh1",n=7,type="discrete")

# Load meta-regressions

# Sari vs. Toci
mr_sari_skeptical = readRDS(here::here("output", "fits",
                                       "mr_sari_skeptical.Rds"))
mr_sari_optimistic_sari_remapcap =
  readRDS(here::here("output", "fits", "sensitivity_analyses",
                     "mr_sari_optimistic_sari_remapcap.Rds"))
mr_sari_optimistic_toci_remapcap =
  readRDS(here::here("output", "fits", "sensitivity_analyses",
                     "mr_sari_optimistic_toci_remapcap.Rds"))


mr_sari_vague = readRDS(here::here("output", "fits",
                                   "mr_sari_vague.Rds"))



# Bari vs. Toci

mr_bari_skeptical = readRDS(here::here("output", "fits",
                                       "mr_bari_skeptical.Rds"))
mr_bari_optimistic_bari = readRDS(here::here("output", "fits",
                                             "mr_bari_optimistic_bari.Rds"))
mr_bari_optimistic_toci = readRDS(here::here("output", "fits",
                                             "mr_bari_optimistic_toci.Rds"))
mr_bari_vague = readRDS(here::here("output", "fits",
                                   "mr_bari_vague.Rds"))

# Sensitivity analysis
mr_bari_skeptical_sens = readRDS(here::here("output", "fits",
                                       "mr_bari_skeptical_sens.Rds"))
mr_bari_optimistic_bari_sens = readRDS(here::here("output", "fits",
                                             "mr_bari_optimistic_bari_sens.Rds"))
mr_bari_optimistic_toci_sens = readRDS(here::here("output", "fits",
                                             "mr_bari_optimistic_toci_sens.Rds"))
mr_bari_vague_sens = readRDS(here::here("output", "fits",
                                   "mr_bari_vague_sens.Rds"))

```


```{r}
ni_margin = log(1.139606)

# Function to plot posterior distributions
plot_fun = function(parameter,
                    color,
                    prior_mean,
                    prior_sd,
                    probability,
                    header){
  parameter |> 
  ggplot(aes(x = value,
             fill = stat(x < ni_margin),
             slab_alpha = stat(desc(x)))) + # https://github.com/mjskay/ggdist/issues/125
  ggdist::stat_halfeye(point_interval = ggdist::median_hdi,
                       .width = 0.95,
                       point_size = 3,
                       fill_type = "gradient",
                       # very important so all distributions are comparable
                       normalize = "none") +
  scale_slab_alpha_continuous(range = c(-0.2, 1.25)) +
  scale_fill_manual(values = c("gray80", color)) +
  # Prior 
  stat_function(fun = dnorm,
                args = c(mean = prior_mean,
                         sd = prior_sd),
                alpha = 0.8, color = "gray50", linetype = 1, size = 0.7) + 
  
  geom_vline(xintercept = ni_margin, linetype = 2, color = "gray50") +
    
  annotate("text", x = log(1.05), y = 4,
           label = probability, size = 5) +
  
  scale_y_continuous(limits = c(0, 4),
                     breaks = seq(0, 4, 2),
                     expand = c(0, 0.4)) +
  scale_x_continuous(breaks = log(c(seq(0.6, 1, 0.2), 1.139606, seq(1, 1.8, 0.4))),
                     limits = log(c(0.5, 2)),
                     labels = c(seq(0.6, 1, 0.2), 1.14, seq(1, 1.8, 0.4))) +
  labs(x = " ",
       y = "Density",
       subtitle = header) +
  ggdist::theme_ggdist() +
  theme(legend.position = 'none',
        plot.subtitle = element_text(hjust = 0.5, # centralize
                                     size=14), 
        plot.title = element_text(hjust = 0.5, # centralize
                                  size=16,
                                  face="bold"),
        plot.margin = margin(20, 20, 0, 20))
}

# Functions to plot arrows below the figure 

# Define general parameters for plots
xlim = c(0, 20)

a_small_amount = abs(xlim[1] - xlim[2])/35

null_line_at = 10

arrow_df = data.frame(id = c(1,2),
                      xstart = c(null_line_at - a_small_amount,
                                      null_line_at + a_small_amount),
                      xend = c(xlim[1] + a_small_amount, xlim[2] - a_small_amount),
                      y = c(1, 1))


arrow_fun = function(output,
                     input){

output = ggplot() +
      geom_segment(data = arrow_df,
                   aes(x = .data$xstart,
                       xend = .data$xend,
                       y = .data$y,
                       yend = .data$y),
                   arrow = arrow(angle = 15, type = "closed", length = grid::unit(0.1, "in"))) +
  
  geom_text(data = input, # Input
            
            aes(x = .data$x,
                y = .data$y,
                label = .data$text,
                hjust = .data$hjust), size = 4) +
  scale_y_continuous(expand = c(0,0), limits = c(-0.5, 1.75)) +
  scale_x_continuous(expand = c(0,0), limits = xlim) +
  theme(panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill = "transparent"),
        legend.box.background = element_rect(fill = "transparent"),
        panel.border = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank())

return(output)
}

labs_bari = c("Favors\nBaricitinib", "Favors\nTocilizumab")


df_bari = data.frame(text = labs_bari,
                     x = c(1,19),
                     y = c(0.2, 0.2),
                     hjust = c(0, 1))

arrows_bari = arrow_fun(arrows_bari, df_bari)

labs_sari = c("Favors\nSarilumab", "Favors\nTocilizumab")


df_sari = data.frame(text = labs_sari,
                     x = c(1,19),
                     y = c(0.2, 0.2),
                     hjust = c(0, 1))

arrows_sari = arrow_fun(arrows_sari, df_sari)

# Function to extract posterior draws more easily

parameter_fun = function(model){
  model |>
    tidybayes::tidy_draws() |>
    tidyr::pivot_longer(5) # Beta_1 parameter (5th column)
}
  
```

# Main analysis

```{r}
# Prior information

## Means
mean_log_bari = log(0.9)

mean_skeptical = log(1)

## SDs

# Assuming a mean = log(1), what is the SD that yields a distribution
# with 0.025 probability density below log(0.5)?
bari_sd_skeptical = (mean_skeptical - log(0.5))/qnorm(1-0.025)

# Assuming a mean = log(0.9), what is the SD that yields a distribution
# with 0.4 probability density above log(1)?
bari_sd_optimistic_bari = (log(1) - mean_log_bari)/qnorm(1-0.4)

# Assuming a mean = log(1/0.9) = -log(0.9), what is the SD that yields a
# distribution with 0.4 probability density below log(1)?
bari_sd_optimistic_toci = (-mean_log_bari - log(1))/qnorm(1-0.4)

bari_sd_vague = 4
```


```{r}
draws_bari =
  dplyr::tibble(
    "vague" = parameter_fun(mr_bari_vague)$value,
    "skeptical" = parameter_fun(mr_bari_skeptical)$value,
    "optimistic_bari" = parameter_fun(mr_bari_optimistic_bari)$value,
    "optimistic_toci" = parameter_fun(mr_bari_optimistic_toci)$value
  ) |> 
  tidyr::pivot_longer(1:4)

probs_bari = 
  draws_bari |> 
  dplyr::group_by(name) |> 
  summarise(prNI = stringr::str_c(
    round(100*mean(value < ni_margin)), "%")
    )

p1 = plot_fun(parameter = parameter_fun(mr_bari_vague),
              color = "#E0C6B6",
              prior_mean = mean_skeptical,
              prior_sd = bari_sd_vague,
              probability = probs_bari[[4,2]],
              header = "Vague") +
  ggplot2::labs(title = "Baricitinib vs. Tocilizumab\n")

p2 = plot_fun(parameter = parameter_fun(mr_bari_skeptical),
              color = "gray50",
              prior_mean = mean_skeptical,
              prior_sd = bari_sd_skeptical,
              probability = probs_bari[[3,2]],
              header = "Skeptical")

p3 = plot_fun(parameter = parameter_fun(mr_bari_optimistic_bari),
              color = pal_bari_sari[3],
              prior_mean = mean_log_bari,
              prior_sd = bari_sd_optimistic_bari,
              probability = probs_bari[[1,2]],
              header = "Optimistic for Baricitinib")

p4 = plot_fun(parameter = parameter_fun(mr_bari_optimistic_toci),
              color = pal_toci[6],
              prior_mean = -mean_log_bari,
              prior_sd = bari_sd_optimistic_toci,
              probability = probs_bari[[2,2]],
              header = "Optimistic for Tocilizumab") +
  theme(plot.margin = margin(20, 20, 40, 20))

p_bari = 
  (p1 / p2 / p3 / p4 + 
  inset_element(arrows_bari,
                ignore_tag = TRUE,
                align_to = "full",
                left = unit(1.75, 'cm'),
                bottom = unit(0.2, 'cm'),
                right = unit(14, 'cm'),
                top = unit(2.5, 'cm')) 
  )
```


```{r meta regressions sensitivity prior info}
## Means

# Source: Figure S3, Appendix Appendix page 46 
# https://www.medrxiv.org/content/10.1101/2021.06.18.21259133v2.Appendix-material
# version posted June 22, 2021
reciprocal_remap_cap = 1/1.05
mean_log_sari = log(reciprocal_remap_cap)

mean_skeptical = log(1)

## SDs

# Assuming a mean = log(1), what is the SD that yields a distribution
# with 0.025 probability density below log(0.5)?
sari_sd_skeptical = (mean_skeptical - log(0.5))/qnorm(1-0.025)

# Formula to extract standard error (SE)

# Transform the results into the log scale and calculate the SE
# https://training.cochrane.org/handbook/current/chapter-06#section-6-3-2

width = log(1.35) - log(0.85)

sari_sd_optimistic_sari = width/(2*1.96)
sari_sd_optimistic_toci = sari_sd_optimistic_sari

sari_sd_vague = 4
```

```{r}
draws_sari =
  dplyr::tibble(
    "vague" = parameter_fun(mr_sari_vague)$value,
    "skeptical" = parameter_fun(mr_sari_skeptical)$value,
    "optimistic_sari" = parameter_fun(mr_sari_optimistic_sari_remapcap)$value,
    "optimistic_toci" = parameter_fun(mr_sari_optimistic_toci_remapcap)$value
  ) |> 
  tidyr::pivot_longer(1:4)

probs_sari = 
  draws_sari |> 
  dplyr::group_by(name) |> 
  summarise(prNI = stringr::str_c(
    round(100*mean(value < ni_margin)), "%")
    )

p1 = plot_fun(parameter = parameter_fun(mr_sari_vague),
              color = "#E0C6B6",
              prior_mean = mean_skeptical,
              prior_sd = sari_sd_vague,
              probability = probs_sari[[4,2]],
              header = "Vague") +
  ggplot2::labs(title = "Sarilumab vs. Tocilizumab\n")

p2 = plot_fun(parameter = parameter_fun(mr_sari_skeptical),
              color = "gray50",
              prior_mean = mean_skeptical,
              prior_sd = sari_sd_skeptical,
              probability = probs_sari[[3,2]],
              header = "Skeptical")

p3 = plot_fun(parameter = parameter_fun(mr_sari_optimistic_sari_remapcap),
              color = pal_bari_sari[7],
              prior_mean = mean_log_sari,
              prior_sd = sari_sd_optimistic_sari,
              probability = probs_sari[[1,2]],
              header = "Optimistic for Sarilumab (REMAP-CAP)")

p4 = plot_fun(parameter = parameter_fun(mr_sari_optimistic_toci_remapcap),
              color = pal_toci[6],
              prior_mean = -mean_log_sari,
              prior_sd = sari_sd_optimistic_toci,
              probability = probs_sari[[2,2]],
              header = "Optimistic for Tocilizumab (inverse REMAP-CAP)") +
  theme(plot.margin = margin(20, 20, 40, 20))

p_sari = 
  (p1 / p2 / p3 / p4 + 
  patchwork::inset_element(arrows_sari,
                           ignore_tag = TRUE,
                           align_to = "full",
                           left = unit(1.75, 'cm'),
                           bottom = unit(0.2, 'cm'),
                           right = unit(14, 'cm'),
                           top = unit(2.5, 'cm'))
  )
```

```{r include=FALSE}

p_bari

ggsave(width = 6,
       height = 9,
       device = cairo_pdf,
       here::here("output", "figures", # File path
                  "figure2_panelA_meta_regressions_bari.pdf"))

p_sari

ggsave(width = 6,
       height = 9,
       device = cairo_pdf,
       here::here("output", "figures", # File path
                  "figure2_panelB_meta_regressions_sari.pdf")) # File name
```

```{r fig.align='center'}
p =
  cowplot::ggdraw() + 
  # https://stackoverflow.com/questions/50026862/the-draw-image-function-from-cowplot-results-in-blurred-pdfs
  cowplot::draw_image(
    magick::image_read_pdf(
    here::here("output", "figures",
               "figure2_panelA_meta_regressions_bari.pdf"),
    density = 600),
    x = -0.25, y = 0) +
  
  cowplot::draw_image(
    magick::image_read_pdf(
    here::here("output", "figures",
               "figure2_panelB_meta_regressions_sari.pdf"),
    density = 600),
    x = 0.25, y = 0)

p

ggsave(width = 12,
       height = 9,
       here("output", "figures", # File path
            "figure2_meta_regressions.png")) # File name

ggsave(width = 12,
       height = 9,
       here("output", "figures", # File path
            "figure2_meta_regressions.pdf")) # File name
```

# Sensitivity analysis (Bari)

```{r}
# Prior information

## Means
mean_log_bari = log(0.9)

mean_skeptical = log(1)

## SDs

# Assuming a mean = log(1), what is the SD that yields a distribution
# with 0.025 probability density below log(0.5)?
bari_sd_skeptical = (mean_skeptical - log(0.5))/qnorm(1-0.025)

# Assuming a mean = log(0.9), what is the SD that yields a distribution
# with 0.4 probability density above log(1)?
bari_sd_optimistic_bari = (log(1) - mean_log_bari)/qnorm(1-0.4)

# Assuming a mean = log(1/0.9) = -log(0.9), what is the SD that yields a
# distribution with 0.4 probability density below log(1)?
bari_sd_optimistic_toci = (-mean_log_bari - log(1))/qnorm(1-0.4)

bari_sd_vague = 4
```

```{r}
draws_bari_sens =
  dplyr::tibble(
    "vague" = parameter_fun(mr_bari_vague_sens)$value,
    "skeptical" = parameter_fun(mr_bari_skeptical_sens)$value,
    "optimistic_bari" = parameter_fun(mr_bari_optimistic_bari_sens)$value,
    "optimistic_toci" = parameter_fun(mr_bari_optimistic_toci_sens)$value
  ) |> 
  tidyr::pivot_longer(1:4)

probs_bari_sens = 
  draws_bari_sens |> 
  dplyr::group_by(name) |> 
  summarise(prNI = stringr::str_c(
    round(100*mean(value < ni_margin)), "%")
    )

p1_sens = plot_fun(parameter = parameter_fun(mr_bari_vague_sens),
              color = "#E0C6B6",
              prior_mean = mean_skeptical,
              prior_sd = bari_sd_vague,
              probability = probs_bari_sens[[4,2]],
              header = "Vague") +
  ggplot2::labs(title = "Baricitinib vs. Tocilizumab\n")

p2_sens = plot_fun(parameter = parameter_fun(mr_bari_skeptical_sens),
              color = "gray50",
              prior_mean = mean_skeptical,
              prior_sd = bari_sd_skeptical,
              probability = probs_bari_sens[[3,2]],
              header = "Skeptical")

p3_sens = plot_fun(parameter = parameter_fun(mr_bari_optimistic_bari_sens),
              color = pal_bari_sari[3],
              prior_mean = mean_log_bari,
              prior_sd = bari_sd_optimistic_bari,
              probability = probs_bari_sens[[1,2]],
              header = "Optimistic for Baricitinib")

p4_sens = plot_fun(parameter = parameter_fun(mr_bari_optimistic_toci_sens),
              color = pal_toci[6],
              prior_mean = -mean_log_bari,
              prior_sd = bari_sd_optimistic_toci,
              probability = probs_bari_sens[[2,2]],
              header = "Optimistic for Tocilizumab") +
  theme(plot.margin = margin(20, 20, 40, 20))

p_bari_sens = 
  (p1_sens / p2_sens / p3_sens / p4_sens + 
  inset_element(arrows_bari,
                ignore_tag = TRUE,
                align_to = "full",
                left = unit(1.75, 'cm'),
                bottom = unit(0.2, 'cm'),
                right = unit(14, 'cm'),
                top = unit(2.5, 'cm')) 
  )
```

```{r include=FALSE}

p_bari_sens

ggsave(width = 6,
       height = 9,
       device = cairo_pdf,
       here::here("output", "figures", "supplementary", # File path
                  "baricitinib_meta_regressions_sensitivity.pdf"))
```






